name: markme
description: MarkMe Attendance and Mentoring App for MIT Mysore

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  http: ^1.2.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/mit_college_building.jpg
    - assets/images/mit_logo.png
    - assets/images/aiml_logo.png